version: '3'
services:

  rabbit:
    image: "rabbitmq:3-management"
    environment:
        RABBITMQ_DEFAULT_USER: "rabbitmq"
        RABBITMQ_DEFAULT_PASS: "rabbitmq"
        RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
        RABBITMQ_DEFAULT_VHOST: "/"
    ports:
        - "15672:15672" #Essa é a porta utilizada para a UI.
        - "5672:5672" #Essa é a porta em que nos conectamos com o RabbitMQ.